<h2 align ="center" >Таблица рассчета Жмыха</h2>
	<div class="table" >
	<div class="shrot up one bg-up">Тоннаж\Месяц</div>
	<div class="shrot up bg-up jan">Январь</div>
	<div class="shrot up bg-up feb">Февраль</div>
	<div class="shrot up bg-up aug">Август</div>
	<div class="shrot up bg-up sep">Сентябрь</div>
	<div class="shrot up bg-up oct">Октябрь</div>
	<div class="shrot up bg-up nov">Ноябрь</div>
	<div class="shrot left bg-left one-four">25</div>
	<div class="shrot bgcolor a1">121</div>
	<div class="shrot bgcolor a2">137</div>
	<div class="shrot bgcolor a3">124</div>
	<div class="shrot bgcolor a4">137</div>
	<div class="shrot bgcolor a5">122</div>
	<div class="shrot bgcolor a6">125</div>
	<div class="shrot left bg-left half">50</div>
	<div class="shrot bgcolor b1">118</div>
	<div class="shrot bgcolor b2">121</div>
	<div class="shrot bgcolor b3">145</div>
	<div class="shrot bgcolor b4">147</div>
	<div class="shrot bgcolor b5">143</div>
	<div class="shrot bgcolor b6">145</div>
	<div class="shrot left bg-left three-four">75</div>
	<div class="shrot bgcolor c1">137</div>
	<div class="shrot bgcolor c2">124</div>
	<div class="shrot bgcolor c3">136</div>
	<div class="shrot bgcolor c4">143</div>
	<div class="shrot bgcolor c5">112</div>
	<div class="shrot bgcolor c6">136</div>
	<div class="shrot left bg-left max">100</div>
	<div class="shrot bgcolor d1">142</div>
	<div class="shrot bgcolor d2">131</div>
	<div class="shrot bgcolor d3">138</div>
	<div class="shrot bgcolor d4">112</div>
	<div class="shrot bgcolor d5">117</div>
	<div class="shrot bgcolor d6">138</div>
	</div>